description: Example of TPythonDag with SQL files for debugging and testing
schedule_interval:
factory: Python
default_args:
  owner: airflow
  retries: 1
  retry_delay: 2
  result_type: pickle
  work_type: s3
  work_conn_id: s3
