description: null
schedule_interval: '*/5 * * * *'
default_args:
  owner: airflow
  retries: 1
  result_type: pickle
  work_type: file
factory: YAML
postrun: []
prerun: []
tags: null
tasks:
- conn_id: pg
  task_id: sql
  type: data_detective_airflow.operators.extractors.DBDump
  sql: /code/sql.sql
