/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
 tutorialSidebar: [
     {type: 'doc', id: 'welcome'},
     {
      type: 'category',
      label: 'Data Detective Airflow',
      items: [
          {
              type: 'autogenerated',
              dirName: 'data-detective-airflow',
          },
          {
              type: 'category',
              label: 'Data Detective Airflow API reference',
              items: [{type: 'autogenerated', dirName: 'data_detective_airflow_api_reference'}]
          },
      ],
     },
     {
      type: 'category',
      label: 'Data Detective ETL',
      items: [
          {
              type: 'link',
              label:'Official Github repository',
              href: 'https://github.com/TinkoffCreditSystems/data-detective/tree/master/data-detective-etl',
          },
          {
              type: 'category',
              label: 'Data Detective ETL API reference',
              items: [{type: 'autogenerated', dirName: 'data_detective_etl_api_reference'}]
          },
      ],
     },
 ],
};

module.exports = sidebars;
