/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
 tutorialSidebar: [
     {type: 'doc', id: 'welcome'},
     {
         type: 'category',
         label: 'Data Detective Project',
         items: [
             {
                 type: 'doc',
                 id: 'data-detective/intro',
             },
             {
                 type: 'category',
                 label: 'Logical Model',
                 items: [
                     'logical_model/layers',
                     {
                         type: 'category',
                         label: 'dds',
                         items: [{type: 'autogenerated', dirName: 'logical_model/dds'}]
                     },
                     {
                         type: 'category',
                         label: 'tuning',
                         items: [{type: 'autogenerated', dirName: 'logical_model/tuning'}]
                     }
                 ]
             },
         ],
     },
     {
      type: 'category',
      label: 'Data Detective Airflow',
      items: [
          {
              type: 'doc',
              id: 'data-detective-airflow/intro',
          },
          {
              type: 'doc',
              id: 'data-detective-airflow/quickstart-airflow',
          },
          {
              type: 'category',
              label: 'Tutorial',
              items: ['data-detective-airflow/concepts', 'data-detective-airflow/creating-dag','data-detective-airflow/creating-operator']
          },
          {
              type: 'doc',
              id: 'data-detective-airflow/testing',
          },
          {
              type: 'doc',
              id: 'data-detective-airflow/production',
          },
          {
              type: 'doc',
              id: 'data-detective-airflow/comparison',
          },
          {
              type: 'doc',
              id: 'data-detective-airflow/datasets-abstractions',
          },
          {
              type: 'doc',
              id: 'data-detective-airflow/how-to-release',
          },
          {
              type: 'category',
              label: 'Data Detective Airflow API reference',
              items: [{type: 'autogenerated', dirName: 'data_detective_airflow_api_reference'}]
          },
      ],
     },
     {
      type: 'category',
      label: 'Data Detective ETL',
      items: [
          {
              type: 'link',
              label: 'Official Github repository',
              href: 'https://github.com/TinkoffCreditSystems/data-detective/tree/master/data-detective-etl',
          },
          {
              type: 'doc',
              id: 'data-detective-etl/quickstart-etl',
          },
          {
              type: 'category',
              label: 'Description of classes and methods',
              items: [{type: 'autogenerated', dirName: 'data_detective_etl_api_reference'}]
          },
      ],
     },
 ],
};

module.exports = sidebars;
