description: Загрузка корневых сущностей
schedule_interval: '5 1 * * *'
tags:
  - tuning
default_args:
  owner: airflow
  result_type: pickle
  retries: 1
  work_type: file
factory: YAML
tasks:

  - task_id: dump_root_nodes_entities
    description: Создать tree_nod'ы
    type: data_detective_airflow.operators.PythonDump
    python_callable: dump_root_nodes_entities
    op_kwargs:
      file_name: root_nodes.yaml

  - task_id: dump_root_nodes_relations
    description: Создать связи между tree_nod'ами
    type: data_detective_airflow.operators.PythonDump
    python_callable: dump_root_nodes_relations
    op_kwargs:
      file_name: root_nodes.yaml

  - description: Заливаем в dds.entity
    type: data_detective_airflow.operators.upload_mg_entity
    sources:
    - dump_root_nodes_entities

  - description: Заливаем в dds.relations
    type: data_detective_airflow.operators.upload_mg_relation
    sources:
    - dump_root_nodes_relations
