description: Loading root entities
schedule_interval: '5 1 * * *'
tags:
  - tuning
default_args:
  owner: airflow
  result_type: pickle
  retries: 1
  work_type: file
factory: YAML
tasks:

  - task_id: dump_root_nodes_entities
    description: Generate tree nodes
    type: data_detective_airflow.operators.PythonDump
    python_callable: dump_root_nodes_entities
    op_kwargs:
      file_name: root_nodes.yaml

  - task_id: dump_root_nodes_relations
    description: Create relations between tree nodes
    type: data_detective_airflow.operators.PythonDump
    python_callable: dump_root_nodes_relations
    op_kwargs:
      file_name: root_nodes.yaml

  - description: Upload to dds.entity
    type: data_detective_airflow.operators.upload_mg_entity
    sources:
    - dump_root_nodes_entities

  - description: Upload to dds.relations
    type: data_detective_airflow.operators.upload_mg_relation
    sources:
    - dump_root_nodes_relations
