name: Test data-detective-airflow
on:
  push:
    paths:
      - "data-detective-airflow/**"
      - ".github/workflows/data-detective-airflow-test.yml"
jobs:
  test-mg-airflow:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.9, 3.10 ]
        poetry-version: [ 1.1.13 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |-
          cd data-detective-airflow
          cp .env.example .env
          randstr=`shuf -zer -n32  {A..Z} {a..z} {0..9} | tr -d '\0'`
          echo "SECRET_KEY=${randstr}" >> .env
          echo "PYTHON_VERSION=${{ matrix.python-version }}"  >> .env
          echo "POETRY_VERSION=${{ matrix.poetry-version }}"  >> .env
          docker-compose -f docker-compose.tests.yml up --build --exit-code-from=tests
