name: Test Data Detective ETL
on:
  push:
    paths:
      - "data-detective-etl/**"
      - ".github/workflows/data-detective-etl-test.yml"
jobs:
  test-mg-airflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        working-directory: data-detective-etl
        run: |-
          cp .env.example .env
          randstr=`shuf -zer -n32  {A..Z} {a..z} {0..9} | tr -d '\0'`
          echo "AIRFLOW__WEBSERVER__SECRET_KEY=${randstr}" >> .env
          make tests
