name: Test data-detective-airflow
on:
  push:
    paths:
      - "data-detective-airflow/**"
      - ".github/workflows/data-detective-airflow-test.yml"
jobs:
  test-mg-airflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |-
          cd data-detective-airflow
          cp .env.example .env
          randstr=`shuf -zer -n32  {A..Z} {a..z} {0..9} | tr -d '\0'`
          echo "SECRET_KEY=${randstr}" >> .env
          docker-compose -f docker-compose.tests.yml up --build --exit-code-from=tests
